### ISSUE TITLE
How to add the config for unocss-preset-chinese?

### ISSUE THREAD

**Issue by xfq** [kirklin/unocss-preset-chinese#1]
### Additional context

https://github.com/kirklin/unocss-preset-chinese#install

It would be useful to mention where to add the config of this preset, since it's inconsistent with the docs in UnoCSS.

In https://unocss.dev/guide/presets#using-presets , `presetUno` is imported from `unocss` instead of `@unocss/preset-uno`. Moreover, it uses `defineConfig` instead of `UnoCSS`.

**Comment by kirklin** [comment]
Thank you for bringing up this issue. Your observation is indeed valuable.
