### ISSUE TITLE
New names for the Noto CJK fonts

### ISSUE THREAD

**Issue by xfq** [kirklin/unocss-preset-chinese#11]
### Clear and concise description of the problem

According to https://bugs.documentfoundation.org/show_bug.cgi?id=137393 , it looks like Google changed the name of the Noto CJK fonts. So we probably want to add the new names to the font stack.

### Suggested solution

1. In addition to Noto Serif CJK SC, add Noto Serif SC.
2. In addition to Noto Sans CJK SC, add Noto Sans SC.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/kirklin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/kirklin/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kirklin** [comment]
Thanks for addressing the issue related to the Noto CJK fonts' name change. Your proposed solution looks good.

Adding "Noto Serif SC" and "Noto Sans SC" in addition to their previous versions ("Noto Serif CJK SC" and "Noto Sans CJK SC") makes sense, as it ensures compatibility with the new names while maintaining compatibility with the old ones.

Resolving this in version `v0.2.1`.

Great job!
